name: "Test, Build & Deploy (Simulated)"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AI-Powered-Customer-Support-Chatbot-Frontend
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --passWithNoTests

  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AI-Powered-Customer-Support-Chatbot-Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('AI-Powered-Customer-Support-Chatbot-Frontend/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: AI-Powered-Customer-Support-Chatbot-Frontend/.next

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist

      - name: List downloaded files
        run: |
          echo "✅ Build artifact downloaded successfully."
          echo "Contents of ./dist:"
          ls -la ./dist

      - name: Simulate Deployment
        run: |
          echo "🚀 Simulated deployment started..."
          sleep 2
          echo "✅ Deployment completed successfully (simulation)."
